/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiToolsRouteImport } from './routes/api/tools'
import { Route as ApiPromptsRouteImport } from './routes/api/prompts'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppTrainingRouteImport } from './routes/_app/training'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppStorageRouteImport } from './routes/_app/storage'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPromptsRouteImport } from './routes/_app/prompts'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppGdriveRouteImport } from './routes/_app/gdrive'
import { Route as AppDataRouteImport } from './routes/_app/data'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiGatewayIndexRouteImport } from './routes/_app/ai-gateway.index'
import { Route as ApiPromptsIdRouteImport } from './routes/api/prompts/$id'
import { Route as ApiKnowledgeUploadRouteImport } from './routes/api/knowledge/upload'
import { Route as ApiKnowledgeSourcesRouteImport } from './routes/api/knowledge/sources'
import { Route as ApiKnowledgeReindexRouteImport } from './routes/api/knowledge/reindex'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiIntegrationsHealthRouteImport } from './routes/api/integrations/health'
import { Route as ApiGdriveReportRouteImport } from './routes/api/gdrive/report'
import { Route as ApiGdriveFilesRouteImport } from './routes/api/gdrive/files'
import { Route as ApiDataUploadRouteImport } from './routes/api/data/upload'
import { Route as ApiDataJobsRouteImport } from './routes/api/data/jobs'
import { Route as ApiDataAnalyzeRouteImport } from './routes/api/data/analyze'
import { Route as ApiDashboardOverviewRouteImport } from './routes/api/dashboard/overview'
import { Route as ApiAnalyticsOverviewRouteImport } from './routes/api/analytics/overview'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AppSettingsOllamaRouteImport } from './routes/_app/settings.ollama'
import { Route as AppAiGatewayPoliciesRouteImport } from './routes/_app/ai-gateway.policies'
import { Route as AppAiGatewayLogsRouteImport } from './routes/_app/ai-gateway.logs'
import { Route as AppAiGatewayEndpointsRouteImport } from './routes/_app/ai-gateway.endpoints'
import { Route as AppAiGatewayAgentsRouteImport } from './routes/_app/ai-gateway.agents'
import { Route as ApiToolsIdTestRouteImport } from './routes/api/tools/$id/test'
import { Route as ApiPromptsIdTestRouteImport } from './routes/api/prompts/$id/test'
import { Route as ApiKnowledgeSourcesIdRouteImport } from './routes/api/knowledge/sources/$id'
import { Route as ApiJobsIdRetryRouteImport } from './routes/api/jobs/$id/retry'
import { Route as ApiJobsIdCancelRouteImport } from './routes/api/jobs/$id/cancel'
import { Route as ApiIntegrationsConfigStatusRouteImport } from './routes/api/integrations/config/status'
import { Route as ApiIntegrationsConfigSaveRouteImport } from './routes/api/integrations/config/save'
import { Route as ApiIntegrationsIdTestRouteImport } from './routes/api/integrations/$id/test'
import { Route as ApiIntegrationsIdSecretRouteImport } from './routes/api/integrations/$id/secret'
import { Route as ApiDataJobsIdRouteImport } from './routes/api/data/jobs/$id'
import { Route as ApiDataJobsIdSendToKnowledgeBaseRouteImport } from './routes/api/data/jobs/$id/send-to-knowledge-base'
import { Route as ApiDataJobsIdRetryRouteImport } from './routes/api/data/jobs/$id/retry'
import { Route as ApiDataJobsIdExportRouteImport } from './routes/api/data/jobs/$id/export'
import { Route as ApiDataJobsIdApproveRouteImport } from './routes/api/data/jobs/$id/approve'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiToolsRoute = ApiToolsRouteImport.update({
  id: '/api/tools',
  path: '/api/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptsRoute = ApiPromptsRouteImport.update({
  id: '/api/prompts',
  path: '/api/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppGdriveRoute = AppGdriveRouteImport.update({
  id: '/gdrive',
  path: '/gdrive',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGatewayIndexRoute = AppAiGatewayIndexRouteImport.update({
  id: '/ai-gateway/',
  path: '/ai-gateway/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPromptsIdRoute = ApiPromptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPromptsRoute,
} as any)
const ApiKnowledgeUploadRoute = ApiKnowledgeUploadRouteImport.update({
  id: '/api/knowledge/upload',
  path: '/api/knowledge/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSourcesRoute = ApiKnowledgeSourcesRouteImport.update({
  id: '/api/knowledge/sources',
  path: '/api/knowledge/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeReindexRoute = ApiKnowledgeReindexRouteImport.update({
  id: '/api/knowledge/reindex',
  path: '/api/knowledge/reindex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiIntegrationsHealthRoute = ApiIntegrationsHealthRouteImport.update({
  id: '/api/integrations/health',
  path: '/api/integrations/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGdriveReportRoute = ApiGdriveReportRouteImport.update({
  id: '/api/gdrive/report',
  path: '/api/gdrive/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGdriveFilesRoute = ApiGdriveFilesRouteImport.update({
  id: '/api/gdrive/files',
  path: '/api/gdrive/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataUploadRoute = ApiDataUploadRouteImport.update({
  id: '/api/data/upload',
  path: '/api/data/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataJobsRoute = ApiDataJobsRouteImport.update({
  id: '/api/data/jobs',
  path: '/api/data/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataAnalyzeRoute = ApiDataAnalyzeRouteImport.update({
  id: '/api/data/analyze',
  path: '/api/data/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardOverviewRoute = ApiDashboardOverviewRouteImport.update({
  id: '/api/dashboard/overview',
  path: '/api/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsOverviewRoute = ApiAnalyticsOverviewRouteImport.update({
  id: '/api/analytics/overview',
  path: '/api/analytics/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsOllamaRoute = AppSettingsOllamaRouteImport.update({
  id: '/ollama',
  path: '/ollama',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAiGatewayPoliciesRoute = AppAiGatewayPoliciesRouteImport.update({
  id: '/ai-gateway/policies',
  path: '/ai-gateway/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGatewayLogsRoute = AppAiGatewayLogsRouteImport.update({
  id: '/ai-gateway/logs',
  path: '/ai-gateway/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGatewayEndpointsRoute = AppAiGatewayEndpointsRouteImport.update({
  id: '/ai-gateway/endpoints',
  path: '/ai-gateway/endpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGatewayAgentsRoute = AppAiGatewayAgentsRouteImport.update({
  id: '/ai-gateway/agents',
  path: '/ai-gateway/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiToolsIdTestRoute = ApiToolsIdTestRouteImport.update({
  id: '/$id/test',
  path: '/$id/test',
  getParentRoute: () => ApiToolsRoute,
} as any)
const ApiPromptsIdTestRoute = ApiPromptsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiPromptsIdRoute,
} as any)
const ApiKnowledgeSourcesIdRoute = ApiKnowledgeSourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiKnowledgeSourcesRoute,
} as any)
const ApiJobsIdRetryRoute = ApiJobsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiJobsIdCancelRoute = ApiJobsIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiIntegrationsConfigStatusRoute =
  ApiIntegrationsConfigStatusRouteImport.update({
    id: '/api/integrations/config/status',
    path: '/api/integrations/config/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsConfigSaveRoute =
  ApiIntegrationsConfigSaveRouteImport.update({
    id: '/api/integrations/config/save',
    path: '/api/integrations/config/save',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsIdTestRoute = ApiIntegrationsIdTestRouteImport.update({
  id: '/api/integrations/$id/test',
  path: '/api/integrations/$id/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsIdSecretRoute = ApiIntegrationsIdSecretRouteImport.update({
  id: '/api/integrations/$id/secret',
  path: '/api/integrations/$id/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataJobsIdRoute = ApiDataJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDataJobsRoute,
} as any)
const ApiDataJobsIdSendToKnowledgeBaseRoute =
  ApiDataJobsIdSendToKnowledgeBaseRouteImport.update({
    id: '/send-to-knowledge-base',
    path: '/send-to-knowledge-base',
    getParentRoute: () => ApiDataJobsIdRoute,
  } as any)
const ApiDataJobsIdRetryRoute = ApiDataJobsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiDataJobsIdRoute,
} as any)
const ApiDataJobsIdExportRoute = ApiDataJobsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiDataJobsIdRoute,
} as any)
const ApiDataJobsIdApproveRoute = ApiDataJobsIdApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiDataJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/data': typeof AppDataRoute
  '/gdrive': typeof AppGdriveRoute
  '/integrations': typeof AppIntegrationsRoute
  '/jobs': typeof AppJobsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/storage': typeof AppStorageRoute
  '/tools': typeof AppToolsRoute
  '/training': typeof AppTrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/prompts': typeof ApiPromptsRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/ai-gateway/agents': typeof AppAiGatewayAgentsRoute
  '/ai-gateway/endpoints': typeof AppAiGatewayEndpointsRoute
  '/ai-gateway/logs': typeof AppAiGatewayLogsRoute
  '/ai-gateway/policies': typeof AppAiGatewayPoliciesRoute
  '/settings/ollama': typeof AppSettingsOllamaRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/data/analyze': typeof ApiDataAnalyzeRoute
  '/api/data/jobs': typeof ApiDataJobsRouteWithChildren
  '/api/data/upload': typeof ApiDataUploadRoute
  '/api/gdrive/files': typeof ApiGdriveFilesRoute
  '/api/gdrive/report': typeof ApiGdriveReportRoute
  '/api/integrations/health': typeof ApiIntegrationsHealthRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/knowledge/reindex': typeof ApiKnowledgeReindexRoute
  '/api/knowledge/sources': typeof ApiKnowledgeSourcesRouteWithChildren
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/prompts/$id': typeof ApiPromptsIdRouteWithChildren
  '/ai-gateway/': typeof AppAiGatewayIndexRoute
  '/api/data/jobs/$id': typeof ApiDataJobsIdRouteWithChildren
  '/api/integrations/$id/secret': typeof ApiIntegrationsIdSecretRoute
  '/api/integrations/$id/test': typeof ApiIntegrationsIdTestRoute
  '/api/integrations/config/save': typeof ApiIntegrationsConfigSaveRoute
  '/api/integrations/config/status': typeof ApiIntegrationsConfigStatusRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/api/knowledge/sources/$id': typeof ApiKnowledgeSourcesIdRoute
  '/api/prompts/$id/test': typeof ApiPromptsIdTestRoute
  '/api/tools/$id/test': typeof ApiToolsIdTestRoute
  '/api/data/jobs/$id/approve': typeof ApiDataJobsIdApproveRoute
  '/api/data/jobs/$id/export': typeof ApiDataJobsIdExportRoute
  '/api/data/jobs/$id/retry': typeof ApiDataJobsIdRetryRoute
  '/api/data/jobs/$id/send-to-knowledge-base': typeof ApiDataJobsIdSendToKnowledgeBaseRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/data': typeof AppDataRoute
  '/gdrive': typeof AppGdriveRoute
  '/integrations': typeof AppIntegrationsRoute
  '/jobs': typeof AppJobsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/storage': typeof AppStorageRoute
  '/tools': typeof AppToolsRoute
  '/training': typeof AppTrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/prompts': typeof ApiPromptsRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/': typeof AppIndexRoute
  '/ai-gateway/agents': typeof AppAiGatewayAgentsRoute
  '/ai-gateway/endpoints': typeof AppAiGatewayEndpointsRoute
  '/ai-gateway/logs': typeof AppAiGatewayLogsRoute
  '/ai-gateway/policies': typeof AppAiGatewayPoliciesRoute
  '/settings/ollama': typeof AppSettingsOllamaRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/data/analyze': typeof ApiDataAnalyzeRoute
  '/api/data/jobs': typeof ApiDataJobsRouteWithChildren
  '/api/data/upload': typeof ApiDataUploadRoute
  '/api/gdrive/files': typeof ApiGdriveFilesRoute
  '/api/gdrive/report': typeof ApiGdriveReportRoute
  '/api/integrations/health': typeof ApiIntegrationsHealthRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/knowledge/reindex': typeof ApiKnowledgeReindexRoute
  '/api/knowledge/sources': typeof ApiKnowledgeSourcesRouteWithChildren
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/prompts/$id': typeof ApiPromptsIdRouteWithChildren
  '/ai-gateway': typeof AppAiGatewayIndexRoute
  '/api/data/jobs/$id': typeof ApiDataJobsIdRouteWithChildren
  '/api/integrations/$id/secret': typeof ApiIntegrationsIdSecretRoute
  '/api/integrations/$id/test': typeof ApiIntegrationsIdTestRoute
  '/api/integrations/config/save': typeof ApiIntegrationsConfigSaveRoute
  '/api/integrations/config/status': typeof ApiIntegrationsConfigStatusRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/api/knowledge/sources/$id': typeof ApiKnowledgeSourcesIdRoute
  '/api/prompts/$id/test': typeof ApiPromptsIdTestRoute
  '/api/tools/$id/test': typeof ApiToolsIdTestRoute
  '/api/data/jobs/$id/approve': typeof ApiDataJobsIdApproveRoute
  '/api/data/jobs/$id/export': typeof ApiDataJobsIdExportRoute
  '/api/data/jobs/$id/retry': typeof ApiDataJobsIdRetryRoute
  '/api/data/jobs/$id/send-to-knowledge-base': typeof ApiDataJobsIdSendToKnowledgeBaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/data': typeof AppDataRoute
  '/_app/gdrive': typeof AppGdriveRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/storage': typeof AppStorageRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/training': typeof AppTrainingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/prompts': typeof ApiPromptsRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ai-gateway/agents': typeof AppAiGatewayAgentsRoute
  '/_app/ai-gateway/endpoints': typeof AppAiGatewayEndpointsRoute
  '/_app/ai-gateway/logs': typeof AppAiGatewayLogsRoute
  '/_app/ai-gateway/policies': typeof AppAiGatewayPoliciesRoute
  '/_app/settings/ollama': typeof AppSettingsOllamaRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/data/analyze': typeof ApiDataAnalyzeRoute
  '/api/data/jobs': typeof ApiDataJobsRouteWithChildren
  '/api/data/upload': typeof ApiDataUploadRoute
  '/api/gdrive/files': typeof ApiGdriveFilesRoute
  '/api/gdrive/report': typeof ApiGdriveReportRoute
  '/api/integrations/health': typeof ApiIntegrationsHealthRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/knowledge/reindex': typeof ApiKnowledgeReindexRoute
  '/api/knowledge/sources': typeof ApiKnowledgeSourcesRouteWithChildren
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/prompts/$id': typeof ApiPromptsIdRouteWithChildren
  '/_app/ai-gateway/': typeof AppAiGatewayIndexRoute
  '/api/data/jobs/$id': typeof ApiDataJobsIdRouteWithChildren
  '/api/integrations/$id/secret': typeof ApiIntegrationsIdSecretRoute
  '/api/integrations/$id/test': typeof ApiIntegrationsIdTestRoute
  '/api/integrations/config/save': typeof ApiIntegrationsConfigSaveRoute
  '/api/integrations/config/status': typeof ApiIntegrationsConfigStatusRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/retry': typeof ApiJobsIdRetryRoute
  '/api/knowledge/sources/$id': typeof ApiKnowledgeSourcesIdRoute
  '/api/prompts/$id/test': typeof ApiPromptsIdTestRoute
  '/api/tools/$id/test': typeof ApiToolsIdTestRoute
  '/api/data/jobs/$id/approve': typeof ApiDataJobsIdApproveRoute
  '/api/data/jobs/$id/export': typeof ApiDataJobsIdExportRoute
  '/api/data/jobs/$id/retry': typeof ApiDataJobsIdRetryRoute
  '/api/data/jobs/$id/send-to-knowledge-base': typeof ApiDataJobsIdSendToKnowledgeBaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/chat'
    | '/data'
    | '/gdrive'
    | '/integrations'
    | '/jobs'
    | '/knowledge'
    | '/prompts'
    | '/settings'
    | '/storage'
    | '/tools'
    | '/training'
    | '/api/chat'
    | '/api/jobs'
    | '/api/prompts'
    | '/api/tools'
    | '/ai-gateway/agents'
    | '/ai-gateway/endpoints'
    | '/ai-gateway/logs'
    | '/ai-gateway/policies'
    | '/settings/ollama'
    | '/api/ai/chat'
    | '/api/analytics/overview'
    | '/api/dashboard/overview'
    | '/api/data/analyze'
    | '/api/data/jobs'
    | '/api/data/upload'
    | '/api/gdrive/files'
    | '/api/gdrive/report'
    | '/api/integrations/health'
    | '/api/jobs/$id'
    | '/api/knowledge/reindex'
    | '/api/knowledge/sources'
    | '/api/knowledge/upload'
    | '/api/prompts/$id'
    | '/ai-gateway/'
    | '/api/data/jobs/$id'
    | '/api/integrations/$id/secret'
    | '/api/integrations/$id/test'
    | '/api/integrations/config/save'
    | '/api/integrations/config/status'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/api/knowledge/sources/$id'
    | '/api/prompts/$id/test'
    | '/api/tools/$id/test'
    | '/api/data/jobs/$id/approve'
    | '/api/data/jobs/$id/export'
    | '/api/data/jobs/$id/retry'
    | '/api/data/jobs/$id/send-to-knowledge-base'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/chat'
    | '/data'
    | '/gdrive'
    | '/integrations'
    | '/jobs'
    | '/knowledge'
    | '/prompts'
    | '/settings'
    | '/storage'
    | '/tools'
    | '/training'
    | '/api/chat'
    | '/api/jobs'
    | '/api/prompts'
    | '/api/tools'
    | '/'
    | '/ai-gateway/agents'
    | '/ai-gateway/endpoints'
    | '/ai-gateway/logs'
    | '/ai-gateway/policies'
    | '/settings/ollama'
    | '/api/ai/chat'
    | '/api/analytics/overview'
    | '/api/dashboard/overview'
    | '/api/data/analyze'
    | '/api/data/jobs'
    | '/api/data/upload'
    | '/api/gdrive/files'
    | '/api/gdrive/report'
    | '/api/integrations/health'
    | '/api/jobs/$id'
    | '/api/knowledge/reindex'
    | '/api/knowledge/sources'
    | '/api/knowledge/upload'
    | '/api/prompts/$id'
    | '/ai-gateway'
    | '/api/data/jobs/$id'
    | '/api/integrations/$id/secret'
    | '/api/integrations/$id/test'
    | '/api/integrations/config/save'
    | '/api/integrations/config/status'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/api/knowledge/sources/$id'
    | '/api/prompts/$id/test'
    | '/api/tools/$id/test'
    | '/api/data/jobs/$id/approve'
    | '/api/data/jobs/$id/export'
    | '/api/data/jobs/$id/retry'
    | '/api/data/jobs/$id/send-to-knowledge-base'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/analytics'
    | '/_app/chat'
    | '/_app/data'
    | '/_app/gdrive'
    | '/_app/integrations'
    | '/_app/jobs'
    | '/_app/knowledge'
    | '/_app/prompts'
    | '/_app/settings'
    | '/_app/storage'
    | '/_app/tools'
    | '/_app/training'
    | '/api/chat'
    | '/api/jobs'
    | '/api/prompts'
    | '/api/tools'
    | '/_app/'
    | '/_app/ai-gateway/agents'
    | '/_app/ai-gateway/endpoints'
    | '/_app/ai-gateway/logs'
    | '/_app/ai-gateway/policies'
    | '/_app/settings/ollama'
    | '/api/ai/chat'
    | '/api/analytics/overview'
    | '/api/dashboard/overview'
    | '/api/data/analyze'
    | '/api/data/jobs'
    | '/api/data/upload'
    | '/api/gdrive/files'
    | '/api/gdrive/report'
    | '/api/integrations/health'
    | '/api/jobs/$id'
    | '/api/knowledge/reindex'
    | '/api/knowledge/sources'
    | '/api/knowledge/upload'
    | '/api/prompts/$id'
    | '/_app/ai-gateway/'
    | '/api/data/jobs/$id'
    | '/api/integrations/$id/secret'
    | '/api/integrations/$id/test'
    | '/api/integrations/config/save'
    | '/api/integrations/config/status'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/retry'
    | '/api/knowledge/sources/$id'
    | '/api/prompts/$id/test'
    | '/api/tools/$id/test'
    | '/api/data/jobs/$id/approve'
    | '/api/data/jobs/$id/export'
    | '/api/data/jobs/$id/retry'
    | '/api/data/jobs/$id/send-to-knowledge-base'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  ApiPromptsRoute: typeof ApiPromptsRouteWithChildren
  ApiToolsRoute: typeof ApiToolsRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAnalyticsOverviewRoute: typeof ApiAnalyticsOverviewRoute
  ApiDashboardOverviewRoute: typeof ApiDashboardOverviewRoute
  ApiDataAnalyzeRoute: typeof ApiDataAnalyzeRoute
  ApiDataJobsRoute: typeof ApiDataJobsRouteWithChildren
  ApiDataUploadRoute: typeof ApiDataUploadRoute
  ApiGdriveFilesRoute: typeof ApiGdriveFilesRoute
  ApiGdriveReportRoute: typeof ApiGdriveReportRoute
  ApiIntegrationsHealthRoute: typeof ApiIntegrationsHealthRoute
  ApiKnowledgeReindexRoute: typeof ApiKnowledgeReindexRoute
  ApiKnowledgeSourcesRoute: typeof ApiKnowledgeSourcesRouteWithChildren
  ApiKnowledgeUploadRoute: typeof ApiKnowledgeUploadRoute
  ApiIntegrationsIdSecretRoute: typeof ApiIntegrationsIdSecretRoute
  ApiIntegrationsIdTestRoute: typeof ApiIntegrationsIdTestRoute
  ApiIntegrationsConfigSaveRoute: typeof ApiIntegrationsConfigSaveRoute
  ApiIntegrationsConfigStatusRoute: typeof ApiIntegrationsConfigStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tools': {
      id: '/api/tools'
      path: '/api/tools'
      fullPath: '/api/tools'
      preLoaderRoute: typeof ApiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompts': {
      id: '/api/prompts'
      path: '/api/prompts'
      fullPath: '/api/prompts'
      preLoaderRoute: typeof ApiPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gdrive': {
      id: '/_app/gdrive'
      path: '/gdrive'
      fullPath: '/gdrive'
      preLoaderRoute: typeof AppGdriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-gateway/': {
      id: '/_app/ai-gateway/'
      path: '/ai-gateway'
      fullPath: '/ai-gateway/'
      preLoaderRoute: typeof AppAiGatewayIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/prompts/$id': {
      id: '/api/prompts/$id'
      path: '/$id'
      fullPath: '/api/prompts/$id'
      preLoaderRoute: typeof ApiPromptsIdRouteImport
      parentRoute: typeof ApiPromptsRoute
    }
    '/api/knowledge/upload': {
      id: '/api/knowledge/upload'
      path: '/api/knowledge/upload'
      fullPath: '/api/knowledge/upload'
      preLoaderRoute: typeof ApiKnowledgeUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/sources': {
      id: '/api/knowledge/sources'
      path: '/api/knowledge/sources'
      fullPath: '/api/knowledge/sources'
      preLoaderRoute: typeof ApiKnowledgeSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/reindex': {
      id: '/api/knowledge/reindex'
      path: '/api/knowledge/reindex'
      fullPath: '/api/knowledge/reindex'
      preLoaderRoute: typeof ApiKnowledgeReindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/integrations/health': {
      id: '/api/integrations/health'
      path: '/api/integrations/health'
      fullPath: '/api/integrations/health'
      preLoaderRoute: typeof ApiIntegrationsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gdrive/report': {
      id: '/api/gdrive/report'
      path: '/api/gdrive/report'
      fullPath: '/api/gdrive/report'
      preLoaderRoute: typeof ApiGdriveReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gdrive/files': {
      id: '/api/gdrive/files'
      path: '/api/gdrive/files'
      fullPath: '/api/gdrive/files'
      preLoaderRoute: typeof ApiGdriveFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/upload': {
      id: '/api/data/upload'
      path: '/api/data/upload'
      fullPath: '/api/data/upload'
      preLoaderRoute: typeof ApiDataUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/jobs': {
      id: '/api/data/jobs'
      path: '/api/data/jobs'
      fullPath: '/api/data/jobs'
      preLoaderRoute: typeof ApiDataJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/analyze': {
      id: '/api/data/analyze'
      path: '/api/data/analyze'
      fullPath: '/api/data/analyze'
      preLoaderRoute: typeof ApiDataAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/overview': {
      id: '/api/dashboard/overview'
      path: '/api/dashboard/overview'
      fullPath: '/api/dashboard/overview'
      preLoaderRoute: typeof ApiDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/overview': {
      id: '/api/analytics/overview'
      path: '/api/analytics/overview'
      fullPath: '/api/analytics/overview'
      preLoaderRoute: typeof ApiAnalyticsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/ollama': {
      id: '/_app/settings/ollama'
      path: '/ollama'
      fullPath: '/settings/ollama'
      preLoaderRoute: typeof AppSettingsOllamaRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/ai-gateway/policies': {
      id: '/_app/ai-gateway/policies'
      path: '/ai-gateway/policies'
      fullPath: '/ai-gateway/policies'
      preLoaderRoute: typeof AppAiGatewayPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-gateway/logs': {
      id: '/_app/ai-gateway/logs'
      path: '/ai-gateway/logs'
      fullPath: '/ai-gateway/logs'
      preLoaderRoute: typeof AppAiGatewayLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-gateway/endpoints': {
      id: '/_app/ai-gateway/endpoints'
      path: '/ai-gateway/endpoints'
      fullPath: '/ai-gateway/endpoints'
      preLoaderRoute: typeof AppAiGatewayEndpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-gateway/agents': {
      id: '/_app/ai-gateway/agents'
      path: '/ai-gateway/agents'
      fullPath: '/ai-gateway/agents'
      preLoaderRoute: typeof AppAiGatewayAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tools/$id/test': {
      id: '/api/tools/$id/test'
      path: '/$id/test'
      fullPath: '/api/tools/$id/test'
      preLoaderRoute: typeof ApiToolsIdTestRouteImport
      parentRoute: typeof ApiToolsRoute
    }
    '/api/prompts/$id/test': {
      id: '/api/prompts/$id/test'
      path: '/test'
      fullPath: '/api/prompts/$id/test'
      preLoaderRoute: typeof ApiPromptsIdTestRouteImport
      parentRoute: typeof ApiPromptsIdRoute
    }
    '/api/knowledge/sources/$id': {
      id: '/api/knowledge/sources/$id'
      path: '/$id'
      fullPath: '/api/knowledge/sources/$id'
      preLoaderRoute: typeof ApiKnowledgeSourcesIdRouteImport
      parentRoute: typeof ApiKnowledgeSourcesRoute
    }
    '/api/jobs/$id/retry': {
      id: '/api/jobs/$id/retry'
      path: '/retry'
      fullPath: '/api/jobs/$id/retry'
      preLoaderRoute: typeof ApiJobsIdRetryRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/jobs/$id/cancel': {
      id: '/api/jobs/$id/cancel'
      path: '/cancel'
      fullPath: '/api/jobs/$id/cancel'
      preLoaderRoute: typeof ApiJobsIdCancelRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/integrations/config/status': {
      id: '/api/integrations/config/status'
      path: '/api/integrations/config/status'
      fullPath: '/api/integrations/config/status'
      preLoaderRoute: typeof ApiIntegrationsConfigStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/config/save': {
      id: '/api/integrations/config/save'
      path: '/api/integrations/config/save'
      fullPath: '/api/integrations/config/save'
      preLoaderRoute: typeof ApiIntegrationsConfigSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/$id/test': {
      id: '/api/integrations/$id/test'
      path: '/api/integrations/$id/test'
      fullPath: '/api/integrations/$id/test'
      preLoaderRoute: typeof ApiIntegrationsIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/$id/secret': {
      id: '/api/integrations/$id/secret'
      path: '/api/integrations/$id/secret'
      fullPath: '/api/integrations/$id/secret'
      preLoaderRoute: typeof ApiIntegrationsIdSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/jobs/$id': {
      id: '/api/data/jobs/$id'
      path: '/$id'
      fullPath: '/api/data/jobs/$id'
      preLoaderRoute: typeof ApiDataJobsIdRouteImport
      parentRoute: typeof ApiDataJobsRoute
    }
    '/api/data/jobs/$id/send-to-knowledge-base': {
      id: '/api/data/jobs/$id/send-to-knowledge-base'
      path: '/send-to-knowledge-base'
      fullPath: '/api/data/jobs/$id/send-to-knowledge-base'
      preLoaderRoute: typeof ApiDataJobsIdSendToKnowledgeBaseRouteImport
      parentRoute: typeof ApiDataJobsIdRoute
    }
    '/api/data/jobs/$id/retry': {
      id: '/api/data/jobs/$id/retry'
      path: '/retry'
      fullPath: '/api/data/jobs/$id/retry'
      preLoaderRoute: typeof ApiDataJobsIdRetryRouteImport
      parentRoute: typeof ApiDataJobsIdRoute
    }
    '/api/data/jobs/$id/export': {
      id: '/api/data/jobs/$id/export'
      path: '/export'
      fullPath: '/api/data/jobs/$id/export'
      preLoaderRoute: typeof ApiDataJobsIdExportRouteImport
      parentRoute: typeof ApiDataJobsIdRoute
    }
    '/api/data/jobs/$id/approve': {
      id: '/api/data/jobs/$id/approve'
      path: '/approve'
      fullPath: '/api/data/jobs/$id/approve'
      preLoaderRoute: typeof ApiDataJobsIdApproveRouteImport
      parentRoute: typeof ApiDataJobsIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsOllamaRoute: typeof AppSettingsOllamaRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsOllamaRoute: AppSettingsOllamaRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChatRoute: typeof AppChatRoute
  AppDataRoute: typeof AppDataRoute
  AppGdriveRoute: typeof AppGdriveRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppStorageRoute: typeof AppStorageRoute
  AppToolsRoute: typeof AppToolsRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAiGatewayAgentsRoute: typeof AppAiGatewayAgentsRoute
  AppAiGatewayEndpointsRoute: typeof AppAiGatewayEndpointsRoute
  AppAiGatewayLogsRoute: typeof AppAiGatewayLogsRoute
  AppAiGatewayPoliciesRoute: typeof AppAiGatewayPoliciesRoute
  AppAiGatewayIndexRoute: typeof AppAiGatewayIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChatRoute: AppChatRoute,
  AppDataRoute: AppDataRoute,
  AppGdriveRoute: AppGdriveRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppJobsRoute: AppJobsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppStorageRoute: AppStorageRoute,
  AppToolsRoute: AppToolsRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppIndexRoute: AppIndexRoute,
  AppAiGatewayAgentsRoute: AppAiGatewayAgentsRoute,
  AppAiGatewayEndpointsRoute: AppAiGatewayEndpointsRoute,
  AppAiGatewayLogsRoute: AppAiGatewayLogsRoute,
  AppAiGatewayPoliciesRoute: AppAiGatewayPoliciesRoute,
  AppAiGatewayIndexRoute: AppAiGatewayIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiJobsIdRouteChildren {
  ApiJobsIdCancelRoute: typeof ApiJobsIdCancelRoute
  ApiJobsIdRetryRoute: typeof ApiJobsIdRetryRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdCancelRoute: ApiJobsIdCancelRoute,
  ApiJobsIdRetryRoute: ApiJobsIdRetryRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

interface ApiPromptsIdRouteChildren {
  ApiPromptsIdTestRoute: typeof ApiPromptsIdTestRoute
}

const ApiPromptsIdRouteChildren: ApiPromptsIdRouteChildren = {
  ApiPromptsIdTestRoute: ApiPromptsIdTestRoute,
}

const ApiPromptsIdRouteWithChildren = ApiPromptsIdRoute._addFileChildren(
  ApiPromptsIdRouteChildren,
)

interface ApiPromptsRouteChildren {
  ApiPromptsIdRoute: typeof ApiPromptsIdRouteWithChildren
}

const ApiPromptsRouteChildren: ApiPromptsRouteChildren = {
  ApiPromptsIdRoute: ApiPromptsIdRouteWithChildren,
}

const ApiPromptsRouteWithChildren = ApiPromptsRoute._addFileChildren(
  ApiPromptsRouteChildren,
)

interface ApiToolsRouteChildren {
  ApiToolsIdTestRoute: typeof ApiToolsIdTestRoute
}

const ApiToolsRouteChildren: ApiToolsRouteChildren = {
  ApiToolsIdTestRoute: ApiToolsIdTestRoute,
}

const ApiToolsRouteWithChildren = ApiToolsRoute._addFileChildren(
  ApiToolsRouteChildren,
)

interface ApiDataJobsIdRouteChildren {
  ApiDataJobsIdApproveRoute: typeof ApiDataJobsIdApproveRoute
  ApiDataJobsIdExportRoute: typeof ApiDataJobsIdExportRoute
  ApiDataJobsIdRetryRoute: typeof ApiDataJobsIdRetryRoute
  ApiDataJobsIdSendToKnowledgeBaseRoute: typeof ApiDataJobsIdSendToKnowledgeBaseRoute
}

const ApiDataJobsIdRouteChildren: ApiDataJobsIdRouteChildren = {
  ApiDataJobsIdApproveRoute: ApiDataJobsIdApproveRoute,
  ApiDataJobsIdExportRoute: ApiDataJobsIdExportRoute,
  ApiDataJobsIdRetryRoute: ApiDataJobsIdRetryRoute,
  ApiDataJobsIdSendToKnowledgeBaseRoute: ApiDataJobsIdSendToKnowledgeBaseRoute,
}

const ApiDataJobsIdRouteWithChildren = ApiDataJobsIdRoute._addFileChildren(
  ApiDataJobsIdRouteChildren,
)

interface ApiDataJobsRouteChildren {
  ApiDataJobsIdRoute: typeof ApiDataJobsIdRouteWithChildren
}

const ApiDataJobsRouteChildren: ApiDataJobsRouteChildren = {
  ApiDataJobsIdRoute: ApiDataJobsIdRouteWithChildren,
}

const ApiDataJobsRouteWithChildren = ApiDataJobsRoute._addFileChildren(
  ApiDataJobsRouteChildren,
)

interface ApiKnowledgeSourcesRouteChildren {
  ApiKnowledgeSourcesIdRoute: typeof ApiKnowledgeSourcesIdRoute
}

const ApiKnowledgeSourcesRouteChildren: ApiKnowledgeSourcesRouteChildren = {
  ApiKnowledgeSourcesIdRoute: ApiKnowledgeSourcesIdRoute,
}

const ApiKnowledgeSourcesRouteWithChildren =
  ApiKnowledgeSourcesRoute._addFileChildren(ApiKnowledgeSourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  ApiPromptsRoute: ApiPromptsRouteWithChildren,
  ApiToolsRoute: ApiToolsRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAnalyticsOverviewRoute: ApiAnalyticsOverviewRoute,
  ApiDashboardOverviewRoute: ApiDashboardOverviewRoute,
  ApiDataAnalyzeRoute: ApiDataAnalyzeRoute,
  ApiDataJobsRoute: ApiDataJobsRouteWithChildren,
  ApiDataUploadRoute: ApiDataUploadRoute,
  ApiGdriveFilesRoute: ApiGdriveFilesRoute,
  ApiGdriveReportRoute: ApiGdriveReportRoute,
  ApiIntegrationsHealthRoute: ApiIntegrationsHealthRoute,
  ApiKnowledgeReindexRoute: ApiKnowledgeReindexRoute,
  ApiKnowledgeSourcesRoute: ApiKnowledgeSourcesRouteWithChildren,
  ApiKnowledgeUploadRoute: ApiKnowledgeUploadRoute,
  ApiIntegrationsIdSecretRoute: ApiIntegrationsIdSecretRoute,
  ApiIntegrationsIdTestRoute: ApiIntegrationsIdTestRoute,
  ApiIntegrationsConfigSaveRoute: ApiIntegrationsConfigSaveRoute,
  ApiIntegrationsConfigStatusRoute: ApiIntegrationsConfigStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
